# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#Set this when scaffolding
#Name will appear as part of the specific instance build name in the ADO UI
#name: 'service-C'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '/service-C/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    # echo Add other tasks to build, test, and deploy your project.
    # echo See https://aka.ms/yaml
    printenv | sort
    echo "The name of this service is: $(BUILD.BUILDNUMBER)"
    echo ""
    pwd
    ls -la
    cd $(BUILD.BUILDNUMBER)
    ls -la
  displayName: 'Run a multi-line script'
